; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = minicore8m-bare

; Common settings for all environments
[env]
platform = atmelavr
monitor_speed = 1000000
platform_packages = tool-avrdude@^1.80.1
build_unflags = -Os
build_flags = -O2
    -I lib/avr_drivers/src
    -I lib/avr_drivers/src/core

; Default config for MiniCore @ 16M
[env:minicore]
framework = arduino
board = ATmega328P
board_build.f_cpu = 16000000L
upload_protocol = urclock
upload_speed = 115200

; Default config for MiniCore @ 8M
; Usually this uses internal RC oscillator, 115200 baud is not stable here. 
[env:minicore8m]
framework = arduino
board = ATmega328P
board_build.f_cpu = 8000000L
upload_protocol = urclock
upload_speed = 1000000

; BareMetal config for MiniCore @ 16M
[env:minicore-bare]
board = ATmega328P
board_build.f_cpu = 16000000L
upload_protocol = urclock
upload_speed = 115200

; BareMetal config for MiniCore @ 8M
[env:minicore8m-bare]
board = ATmega328P
board_build.f_cpu = 8000000L
upload_protocol = urclock
upload_speed = 1000000

; Default Arduino Nano config  @ 16M
[env:nanoatmega328new]
board = nanoatmega328new
framework = arduino
